import axios from "../axios";
import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { 
  CognitoIdentityClient,
  GetCredentialsForIdentityCommand,
  GetCredentialsForIdentityCommandInput,
  GetIdCommand,
  GetIdInput,
} from "@aws-sdk/client-cognito-identity";
import { HttpRequest } from '@aws-sdk/protocol-http';
import { Sha256 } from '@aws-crypto/sha256-universal';
import { SignatureV4 } from '@aws-sdk/signature-v4';

export default function Auth() {
  const [response, setResponse] = useState('');

  useEffect(() => {
    auth();
  });

  const auth = async (): Promise<void> => {
    const apiUrl = new URL('https://*****.execute-api.ap-northeast-1.amazonaws.com/api/authorizer/');

    const client = new CognitoIdentityClient({ region: 'ap-northeast-1' });

    // IDプールからidentityIdを取得する
    const idInput: GetIdInput = {
      IdentityPoolId: 'ap-northeast-1:*****',
    };
    const id = await client.send(new GetIdCommand(idInput));

    // identityIdを元に、クレデンシャル情報を取得する
    const credentialsForIdentityCommandInput: GetCredentialsForIdentityCommandInput = {
      IdentityId: id.IdentityId,
    };
    const credentialsForIdentity = await client.send(new GetCredentialsForIdentityCommand(credentialsForIdentityCommandInput));

    // 署名V4を作成する
    const signatureV4 = new SignatureV4({
      service: 'execute-api',
      region: 'ap-northeast-1',
      credentials: {
        accessKeyId: credentialsForIdentity.Credentials?.AccessKeyId!,
        secretAccessKey: credentialsForIdentity.Credentials?.SecretKey!,
        sessionToken: credentialsForIdentity.Credentials?.SessionToken!
      },
      sha256: Sha256,
    });

    // HTTPリクエストを作成する
    const httpRequest = new HttpRequest({
      headers: {
        host: apiUrl.hostname,
      },
      hostname: apiUrl.hostname,
      method: 'GET',
      path: apiUrl.pathname,
    });

    // 署名リクエストを作成する
    const signedRequest = await signatureV4.sign(httpRequest);

    // APIを実行する
    axios.get('https://*****.execute-api.ap-northeast-1.amazonaws.com/api/authorizer/', {
      headers: {
        authorization: signedRequest.headers.authorization,
        'x-amz-content-sha256': signedRequest.headers['x-amz-content-sha256'],
        'x-amz-date': signedRequest.headers['x-amz-date'],
        'x-amz-security-token': signedRequest.headers['x-amz-security-token'],
      }
    })
    .then((response) => {
      setResponse(JSON.stringify(response.data));
    })
    .catch((error) => {
      console.log(error)
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Auth
        </h1>
        <div className={styles.grid}>
          { response }
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
